---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lhx123.
--- DateTime: 2023/11/3 14:54
---


--功能：查询库存，实现一人一单
--参数：优惠券id，用户id

local voucherId = ARGV[1]
local userId = ARGV[2]

--常量
--库存的key
local stockKey = 'seckill:stock:'..voucherId
--订单的key
local orderKey = 'seckill:order:'..voucherId

--查询库存
--判断是否充足
if (tonumber(redis.call('get',stockKey))<=0) then
    --返回1
    return 1
end


--充足判断是否重复下单

if (redis.call('sismember',orderKey,userId)==1) then
    return 2
end

--扣除库存
redis.call('incrby',stockKey,-1)
--新增用户
redis.call('sadd',orderKey,userId)

return 0